stemmer_dict = (
   {'account': {'acc', 'accounts', 'accounting'},
    'accrued': {'acrd'},
    'accrual': {'accruals'},
    'adjustment': {'adjustments'},
    'administration': {'administrations'},
    'aggregate': {'aggregated', 'aggregation'},
    'agreement': {'agreemen', 'agreem'},
    'asset': {'ast'},
    'amortised': {'amortized'},
    'amount': {'amounts', 'amt'},
    'analytic': {'analytical'},
    'application': {'appl'},
    'asset': {'assets'},
    'associate': {'assoc', 'association', 'associating'},
    'authorised': {'authorized'},
    'authorisation': {'autorization'},
    'balance': {'balances', 'bal'},
    'bank': {'bankb', 'banks'},
    'benefit': {'benefits'},
    'binding': {'bind'},
    'cancellation': {'cancelation'},
    'ceiling': {'ceilling'},
    'class': {'classes'},
    'close': {'closed'},
    'code': {'cod'},
    'collateral': {'coll'},
    'commitment': {'commitments'},
    'component': {'components'},
    'compromise': {'compromised'},
    'condition': {'conditions'},
    'confirm': {'conf', 'confirmation', 'confirmed'},
    'construction': {'constr'},
    'contamination': {'contam', 'contaminated'},
    'correction': {'corrected'},
    'contractual': {'ctr'},
    'current': {'curent', 'crt'},
    'customer': {'custome', 'cust', 'customers'},
    'date': {'dt'},
    'database': {'databases', 'db'},
    'day': {'days'},
    'decease': {'deceased'},
    'deferred': {'defered'},
    'deposit': {'deposits', 'depo'},
    'disbursement': {'disbursment'},
    'discount': {'discounted'},
    'display': {'disp'},
    'document': {'documents'},
    'eligible': {'elig', 'eligibility', 'eligbility'},
    'enforce': {'enforcement'},
    'enterprise': {'enterprises'},
    'entity': {'entities'},
    'equity': {'equities'},
    'establish': {'established'},
    'evaluation': {'eval'},
    'expense': {'expenses'},
    'exposure': {'exposures', 'exp'},
    'external': {'ext'},
    'facility': {'facilities'},
    'family': {'familly'},
    'fee': {'fe'},
    'financial': {'fin', 'financed', 'finan', 'finance', 'financing'},
    'flag': {'flags', 'flg'},
    'forced': {'forces'},
    'forex': {'fx'},
    'frequency': {'freq'},
    'fund': {'funds', 'funding'},
    'gross': {'grs'},
    'guarantee': {'guar', 'guaranteed', 'guarantor'},
    'haircut': {'hcut'},
    'hedge': {'hedging'},
    'hierarchy': {'hier'},
    'high': {'higher'},
    'holding': {'holdings'},
    'hour': {'hours'},
    'identifier': {'id', 'identity', 'identif', 'identification'},
    'ifrs': {'ifrs9'},
    'indicator': {'indicators', 'indication'},
    'individual': {'individuals'},
    'ineligibility': {'inelig'},
    'information': {'info'},
    'inherited': {'inheritence'},
    'initial': {'init', 'initiating', 'initiation'},
    'installment': {'instalment', 'installments', 'instalments'},
    'instrument': {'instruments'},
    'insurance': {'insured', 'insurer'},
    'interest': {'int'},
    'invest': {'investor', 'investment', 'investors'},
    'issue': {'issuer', 'issued', 'issuing'},
    'letter': {'letters'},
    'liability': {'liab'},
    'liquidity': {'liq'},
    'list': {'listed'},
    'loan': {'loans'},
    'local': {'loc', 'locality', 'location'},
    'loss': {'losses'},
    'market value': {'fva'},
    'material': {'matl', 'materiality'},
    'maximum': {'max'},
    'measure': {'measurement', 'measurements'},
    'member': {'members'},
    'minimum': {'min', 'minim'},
    'modify': {'modified', 'modification'},
    'month': {'monthly'},
    'national': {'nat'},
    'normalized': {'normalization'},
    'operating': {'oper', 'operation', 'operational', 'operations', 'operative'},
    'option': {'opt'},
    'organization': {'org', 'organisational', 'organisation'},
    'original': {'orig', 'originated', 'origination', 'origin'},
    'other': {'oth'},
    'outstanding': {'outs', 'os'},
    'overdue': {'ovd'},
    'owner': {'own', 'ownership'},
    'parameter': {'parameters'},
    'payment': {'payments'},
    'penalty': {'pen'},
    'person': {'personal', 'personality', 'personnel', 'persons'},
    'political': {'politic'},
    'postponed': {'posponed', 'pospn'},
    'previous': {'prev'},
    'principal': {'prin'},
    'product': {'products'},
    'professional': {'profesional'},
    'program': {'programme'},
    'provision': {'provisions', 'provisioning'},
    'prudential': {'prud'},
    'purchase': {'purchased'},
    'quantity': {'qty'},
    'rate': {'rt'},
    ' ': {'eur', 'lcy', 'ocy'},
    'rating': {'ratings'},
    'reason': {'reasons'},
    'receive': {'received', 'receiving'},
    'reclassify': {'reclassified', 'reclassification'},
    'reconcile': {'reconciled', 'reconciliation'},
    'recover': {'recovered', 'recovery'},
    'reference': {'referance', 'referenced'},
    'register': {'registered', 'registration', 'registry'},
    'reject': {'rejection'},
    'relation': {'rel', 'related', 'relations', 'relationship'},
    'release': {'released'},
    'renew': {'renewal', 'renewed', 'renewable'},
    'repay': {'repayment'},
    'replacement': {'replacements'},
    'residence': {'residency', 'residents'},
    'sale': {'sales'},
    'schema': {'scheme'},
    'secure': {'secured'},
    'segment': {'segmentation'}
    }
)
